### ISSUE TITLE
No Windows support

### ISSUE THREAD

**Issue by thedjinn** [Burgestrand/libspotify#5]
I am trying to use the Spotify gem on Windows, but the gem doesn't provide libspotify's windows binaries.

**Comment by Burgestrand** [comment]
Thanks for the bug report! I’ll see if I can fix this one today.

**Comment by Burgestrand** [comment]
Made a 32-bit gem release now for mingw. Not sure if it will install on cygwin, so if you’re using that please re-open the issue and I’ll investigate if I can install cygwin and see if I can make a build for that as well.

Additionally, you can force install a specific platform by doing `gem install libspotify --platform x86-mingw32`. I believe that should allow you to use the mingw build on cygwin.
