### ISSUE TITLE
Installing libspotify on Windows Server 2008 R2

### ISSUE THREAD

**Issue by george-ayris** [Burgestrand/libspotify#7]
Hi there, 

The install of libspotify is failing on Windows Server 2008 R2 (64-bit/SP1).

Here's the powershell output:

$> gem install libspotify
 Binary libspotify gem could not be installed. You will need to install libspotify separately.
 If you are on ARM (e.g. Raspberry PI), you might want to install the gem with explicit --platform:
 $> gem install libspotify --platform arm-linux
Successfully installed libspotify-12.1.51.4
Parsing documentation for libspotify-12.1.51.4
Installing ri documentation for libspotify-12.1.51.4
Done installing documentation for libspotify after 0 seconds
1 gem installed

Thanks!

**Comment by Burgestrand** [comment]
Hi! Thanks for the bug report :). Could you please show me the output of the following command:

``` ruby
ruby -e 'puts Gem::Platform.local'
```

Also, please keep in mind that there is no 64-bit release of libspotify for windows, which means that your ruby installation will need to be compiled as 32-bit. In the meantime, you should be able to install libspotify and use it with the following command (from #5):

``` bash
gem install libspotify --platform x86-mingw32
```
